spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: ${DRIVERCLASSNAME}

bot:
  token: ${BOT_TOKEN}
  name: ${BOT_NAME}

logging:
  level:
    ru:
      liga: DEBUG
    org:
      springframework:
        beans:
          factory: DEBUG