package ru.liga.statemachine.type;

import lombok.AllArgsConstructor;
import lombok.Getter;
import ru.liga.bot.type.BotCommandType;

@AllArgsConstructor
@Getter
public enum State {
    INITIAL(BotCommandType.START),
    //Cargo
    EDIT_CARGO_TYPE_IN_PROCESS(BotCommandType.EDIT_CARGO_TYPE),
    EDIT_CARGO_TYPE_ID_PROVIDED(BotCommandType.EDIT_CARGO_TYPE),
    EDIT_CARGO_TYPE_NAME_PROVIDED(BotCommandType.EDIT_CARGO_TYPE),
    EDIT_CARGO_TYPE_REPRESENTATION_PROVIDED(BotCommandType.EDIT_CARGO_TYPE),
    ADD_CARGO_TYPE_IN_PROCESS(BotCommandType.ADD_CARGO_TYPE),
    ADD_CARGO_TYPE_NAME_PROVIDED(BotCommandType.ADD_CARGO_TYPE),
    ADD_CARGO_TYPE_REPRESENTATION_PROVIDED(BotCommandType.ADD_TRUCK_TYPE),
    DELETE_CARGO_TYPE_IN_PROCESS(BotCommandType.DELETE_CARGO_TYPE),
    DELETE_CARGO_TYPE_ID_PROVIDED(BotCommandType.DELETE_CARGO_TYPE),
    GET_CARGO_TYPE_IN_PROCESS(BotCommandType.GET_CARGO_TYPES),
    //Truck
    EDIT_TRUCK_TYPE_IN_PROCESS(BotCommandType.GET_CARGO_TYPES),
    EDIT_TRUCK_TYPE_ID_PROVIDED(BotCommandType.EDIT_TRUCK_TYPE),
    EDIT_TRUCK_TYPE_NAME_PROVIDED(BotCommandType.EDIT_TRUCK_TYPE),
    EDIT_TRUCK_HEIGHT_PROVIDED(BotCommandType.EDIT_TRUCK_TYPE),
    EDIT_TRUCK_WIDTH_PROVIDED(BotCommandType.EDIT_TRUCK_TYPE),
    ADD_TRUCK_TYPE_IN_PROCESS(BotCommandType.ADD_TRUCK_TYPE),
    ADD_TRUCK_TYPE_NAME_PROVIDED(BotCommandType.ADD_TRUCK_TYPE),
    ADD_TRUCK_HEIGHT_PROVIDED(BotCommandType.ADD_TRUCK_TYPE),
    ADD_TRUCK_WIDTH_PROVIDED(BotCommandType.ADD_TRUCK_TYPE),
    DELETE_TRUCK_TYPE_IN_PROCESS(BotCommandType.DELETE_TRUCK_TYPE),
    DELETE_TRUCK_TYPE_ID_PROVIDED(BotCommandType.DELETE_TRUCK_TYPE),
    GET_TRUCK_TYPE_IN_PROCESS(BotCommandType.GET_TRUCK_TYPES),
    //Loader
    LOADER_IN_PROCESS(BotCommandType.LOAD_TRUCKS),
    TRUCK_TYPE_PROVIDED(BotCommandType.LOAD_TRUCKS),
    TRUCK_COUNT_PROVIDED(BotCommandType.LOAD_TRUCKS),
    LOADER_TYPE_PROVIDED(BotCommandType.LOAD_TRUCKS),
    CARGOS_PROVIDED(BotCommandType.LOAD_TRUCKS),
    //General
    COMPLETED(BotCommandType.DEFAULT),
    STOP(BotCommandType.DEFAULT),
    CANCELLED(BotCommandType.DEFAULT);

    private final BotCommandType botCommandType;
}
